### ISSUE TITLE
summary html report error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-facilities#14]
I'm getting all the time:
```
DataTables warning: table id=micTable - Requested unknown parameter '0' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4
```

and the table looks like this (ctf time series broken,. table broken):
![image](https://user-images.githubusercontent.com/6952870/101994563-20b1b480-3cbb-11eb-8a5a-18da4617dfa6.png)

PS. I have enabled mic thumbnails generation during motioncor. PSD are properly produced by ctffind

**Comment by pconesa** [comment]
I'm looking into this. In a local case, we are getting the same error and is caused by not having micIds associated with the ctf.

Will you be able to pass me ctfs_log.sqlite (under the summary protocol folder)?

**Comment by azazellochg** [comment]
ehm, no, I do not keep files from Dec 12 2020. You'll have to reproduce this yourself.

**Comment by pconesa** [comment]
Thanks! I'll try.
