### ISSUE TITLE
plugin manager error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-facilities#3]
```
[azazello@xps13-9350 del]$ ./scipion3 plugins
Scipion v3.0 () devel

Warning: Couldn't get remote plugin data for scipion-em-facilities
```

**Comment by pconesa** [comment]
I think it is not deployed yet.

**Comment by dmaluenda** [comment]
Yes, I was waiting to fix a couple of issues, but I think I will deploy it now and I will update it as soon as that fixes arrive..

**Comment by pconesa** [comment]
Seems to be deployed.
https://pypi.org/project/scipion-em-facilities/
